language: php

matrix:
   fast_finish: true
   include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2

before_script:
  - wget -O mailhog https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64
  - chmod +x mailhog
  - (./mailhog -api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -smtp-bind-addr 0.0.0.0:3025 &) > /dev/null 2>&1
  - composer update $COMPOSER_FLAGS

script:
  - make test

cache:
  directories:
    - $HOME/.composer/cache/files
