version: 2
jobs:
  php7.2:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: mailhog/mailhog:v1.0.0
        command: "-api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -smtp-bind-addr 0.0.0.0:3025"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-php7.2-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.2-dependencies-{{ checksum "composer.json" }}
      - run: make test

  php7.3:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: mailhog/mailhog:v1.0.0
        command: "-api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -smtp-bind-addr 0.0.0.0:3025"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-php7.3-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.3-dependencies-{{ checksum "composer.json" }}
      - run: make test

  php7.2-lowest:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: mailhog/mailhog:v1.0.0
        command: "-api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -smtp-bind-addr 0.0.0.0:3025"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-php7.2-lowest-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist --prefer-lowest
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.2-lowest-dependencies-{{ checksum "composer.json" }}
      - run: make test

  php7.3-lowest:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: mailhog/mailhog:v1.0.0
        command: "-api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -smtp-bind-addr 0.0.0.0:3025"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-php7.3-lowest-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist --prefer-lowest
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.3-lowest-dependencies-{{ checksum "composer.json" }}
      - run: make test

workflows:
  version: 2
  commit:
    jobs:
      - php7.2
      - php7.3
      - php7.2-lowest
      - php7.3-lowest
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - php7.2
      - php7.3
      - php7.2-lowest
      - php7.3-lowest
