name: Build

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '51 3 * * 0'

jobs:
  tests:
    services:
      mailhog:
        image: mailhog/mailhog:v1.0.0
        env:
          MH_SMTP_BIND_ADDR: 0.0.0.0:3025
          MH_API_BIND_ADDR: 0.0.0.0:10025
          MH_UI_BIND_ADDR: 0.0.0.0:10025
        ports:
          - 3025:3025
          - 10025:10025
    runs-on: ubuntu-latest
    name: Test
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        composer-flags: [""]
        stability: ["stable"]
        continue-on-composer-error: [""]
        include:
          - php: 7.2
            composer-flags: --prefer-lowest
          - php: 7.3
            composer-flags: --prefer-lowest
          - php: 7.4
            composer-flags: --prefer-lowest
          - php: 8.0
            stability: "dev"
            continue-on-composer-error: true
          - php: 8.0
            stability: "dev"
            composer-flags: --prefer-lowest
            continue-on-composer-error: true

    env:
      COMPOSER_ROOT_VERSION: dev-master

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Update the minimum stability
        if: matrix.stability == 'dev'
        run: composer config minimum-stability ${{ matrix.stability }}

      - name: Install dependencies
        id: composer-run
        continue-on-error: ${{ matrix.continue-on-composer-error }}
        run: composer update ${{ matrix.composer-flags }}

      - name: Run tests
        if: steps.composer-run.outcome == 'success' && steps.composer-run.conclusion == 'success'
        run: make test
